name: ln_dialogs
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/orcunoz/ln_dialogs
publish_to: none

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0
  intl: ^0.18.0
  ln_core:
    git:
      url: https://github.com/orcunoz/ln_core
      ref: main

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
